### ISSUE TITLE
Demos Directory Caching 

### ISSUE THREAD

**Issue by mehrexe** [Narcha/DemoMan#79]
Small suggestion. Add some level of caching to DemoMan to handle large demos directories. Currently, on the Linux tauri build from contents of the current git and the windows exe from release 1.0.7, it takes a few minutes for it to handle/query a ~60 GB demos directory.

**Comment by Narcha** [comment]
Thanks for your suggestion. Something like this will be in v2, I don't plan on implementing it in v1.

**Comment by Narcha** [comment]
Implemented in 1ed8d73babcfd9285b4821b0ad21ff89a9bd4753 and 91ab945c87b4f221474b30b9f28b2af6c77357ca
